--[[
###########################################
Symphony of Souls Quality of Life: keivamp#
###########################################
]]--

local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("font", "Antique_Olive_Bold", [[Interface\AddOns\SoSQOL\Fonts\Antique_Olive_Bold.ttf]])
LSM:Register("font", "BitstreamVeraSerif", [[Interface\AddOns\SoSQOL\Fonts\BitstreamVeraSerif.ttf]])
LSM:Register("font", "Classic", [[Interface\AddOns\SoSQOL\Fonts\Classic.ttf]])
LSM:Register("font", "Cooline", [[Interface\AddOns\SoSQOL\Fonts\Cooline.ttf]])
LSM:Register("font", "Continuum", [[Interface\AddOns\SoSQOL\Fonts\Continuum.ttf]])
LSM:Register("font", "DejaVuSans", [[Interface\AddOns\SoSQOL\Fonts\DejaVuSans.ttf]])
LSM:Register("font", "Daville", [[Interface\AddOns\SoSQOL\Fonts\Daville.ttf]])
LSM:Register("font", "Expressway", [[Interface\AddOns\SoSQOL\Fonts\Expressway.ttf]])
LSM:Register("font", "Emblem", [[Interface\AddOns\SoSQOL\Fonts\Emblem.ttf]])
LSM:Register("font", "Enigmatic", [[Interface\AddOns\SoSQOL\Fonts\Enigmatic.ttf]])
LSM:Register("font", "FuturaBold", [[Interface\AddOns\SoSQOL\Fonts\FuturaBold.ttf]])
LSM:Register("font", "Myriad", [[Interface\AddOns\SoSQOL\Fonts\Myriad.ttf]])
LSM:Register("font", "Pixel", [[Interface\AddOns\SoSQOL\Fonts\Pixel.ttf]])
LSM:Register("font", "Pepsi", [[Interface\AddOns\SoSQOL\Fonts\Pepsi.ttf]])
LSM:Register("font", "Prototype", [[Interface\AddOns\SoSQOL\Fonts\Prototype.ttf]])
LSM:Register("font", "Roboto", [[Interface\AddOns\SoSQOL\Fonts\Roboto.ttf]])
LSM:Register("font", "SF Comic Script", [[Interface\AddOns\SoSQOL\Fonts\SF Comic Script.ttf]])
LSM:Register("font", "Starcraft_Normal", [[Interface\AddOns\SoSQOL\Fonts\Starcraft_Normal.ttf]])
LSM:Register("font", "Transformers", [[Interface\AddOns\SoSQOL\Fonts\Transformers.ttf]])
LSM:Register("font", "Verdana", [[Interface\AddOns\SoSQOL\Fonts\Verdana.ttf]])
LSM:Register("font", "X360", [[Interface\AddOns\SoSQOL\Fonts\X360.ttf]])


LSM:Register("statusbar", "BantoBar", [[Interface\AddOns\SoSQOL\Statusbars\BantoBar.blp]])
LSM:Register("statusbar", "BlueDuo", [[Interface\AddOns\SoSQOL\Statusbars\BlueDuo.blp]])
LSM:Register("statusbar", "BrownShade", [[Interface\AddOns\SoSQOL\Statusbars\BrownShade.blp]])
LSM:Register("statusbar", "BluredRainbow", [[Interface\AddOns\SoSQOL\Statusbars\BluredRainbow.blp]])
LSM:Register("statusbar", "BiShade", [[Interface\AddOns\SoSQOL\Statusbars\BiShade.blp]])
LSM:Register("statusbar", "BottomShade", [[Interface\AddOns\SoSQOL\Statusbars\BottomShade.blp]])
LSM:Register("statusbar", "CellShade", [[Interface\AddOns\SoSQOL\Statusbars\CellShade.blp]])
LSM:Register("statusbar", "Comity", [[Interface\AddOns\SoSQOL\Statusbars\Comity.blp]])
LSM:Register("statusbar", "Courtesy", [[Interface\AddOns\SoSQOL\Statusbars\Courtesy.blp]])
LSM:Register("statusbar", "DarkGrey", [[Interface\AddOns\SoSQOL\Statusbars\DarkGrey.blp]])
LSM:Register("statusbar", "Flat", [[Interface\AddOns\SoSQOL\Statusbars\Flat.blp]])
LSM:Register("statusbar", "Gradient", [[Interface\AddOns\SoSQOL\Statusbars\Gradient.blp]])
LSM:Register("statusbar", "Gloss", [[Interface\AddOns\SoSQOL\Statusbars\Gloss.blp]])
LSM:Register("statusbar", "Glassy", [[Interface\AddOns\SoSQOL\Statusbars\Glassy.blp]])
LSM:Register("statusbar", "LiteStep", [[Interface\AddOns\SoSQOL\Statusbars\LiteStep.blp]])
LSM:Register("statusbar", "LightGrey", [[Interface\AddOns\SoSQOL\Statusbars\LightGrey.blp]])
LSM:Register("statusbar", "LeftShade", [[Interface\AddOns\SoSQOL\Statusbars\LeftShade.blp]])
LSM:Register("statusbar", "Modern", [[Interface\AddOns\SoSQOL\Statusbars\Modern.blp]])
LSM:Register("statusbar", "MediumGrey", [[Interface\AddOns\SoSQOL\Statusbars\MediumGrey.blp]])
LSM:Register("statusbar", "Midline", [[Interface\AddOns\SoSQOL\Statusbars\Midline.blp]])
LSM:Register("statusbar", "OldBook", [[Interface\AddOns\SoSQOL\Statusbars\OldBook.blp]])
LSM:Register("statusbar", "Rainbow", [[Interface\AddOns\SoSQOL\Statusbars\Rainbow.blp]])
LSM:Register("statusbar", "RainbowAgain", [[Interface\AddOns\SoSQOL\Statusbars\RainbowAgain.blp]])
LSM:Register("statusbar", "RainbowAgain2", [[Interface\AddOns\SoSQOL\Statusbars\RainbowAgain2.blp]])
LSM:Register("statusbar", "RainbowAgain3", [[Interface\AddOns\SoSQOL\Statusbars\RainbowAgain3.blp]])
LSM:Register("statusbar", "RainbowAgain4", [[Interface\AddOns\SoSQOL\Statusbars\RainbowAgain4.blp]])
LSM:Register("statusbar", "Reliance", [[Interface\AddOns\SoSQOL\Statusbars\Reliance.blp]])
LSM:Register("statusbar", "RightShade", [[Interface\AddOns\SoSQOL\Statusbars\RightShade.blp]])
LSM:Register("statusbar", "Smooth", [[Interface\AddOns\SoSQOL\Statusbars\Smooth.blp]])
LSM:Register("statusbar", "StopLight", [[Interface\AddOns\SoSQOL\Statusbars\StopLight.blp]])
LSM:Register("statusbar", "Solicitude", [[Interface\AddOns\SoSQOL\Statusbars\Solicitude.blp]])
LSM:Register("statusbar", "SwirlyRainbows", [[Interface\AddOns\SoSQOL\Statusbars\SwirlyRainbows.blp]])
LSM:Register("statusbar", "TwoTone", [[Interface\AddOns\SoSQOL\Statusbars\TwoTone.blp]])
LSM:Register("statusbar", "Tanner", [[Interface\AddOns\SoSQOL\Statusbars\Tanner.blp]])
LSM:Register("statusbar", "TopShade", [[Interface\AddOns\SoSQOL\Statusbars\TopShade.blp]])
LSM:Register("statusbar", "Twizlight", [[Interface\AddOns\SoSQOL\Statusbars\Twizlight.blp]])
LSM:Register("statusbar", "Veracity", [[Interface\AddOns\SoSQOL\Statusbars\Veracity.blp]])
